### ISSUE TITLE
CloseableIterator's closable version of GroupedIterator is never used

### ISSUE THREAD

**Issue by maxaf** [novus/novus-jdbc#4]
When consuming an iterator produced by calling `CloseableIterator#sliding` (or any other inherited method that uses `GroupedIterator`), `CloseableIterator`'s inner `GroupedIterator` - which is supposed to override the supertype's corresponding inner class - doesn't actually override anything and isn't used by the supertype's non-overridden methods.

**Comment by wheaties** [comment]
I've added override to the grouped and sliding methods to `CloseableIterator`, hopefully that should resolve the issues you're seeing.
